services:
    pgvector:
      image: 'pgvector/pgvector:pg16'
      environment:
        - 'POSTGRES_DB=mydatabase'
        - 'POSTGRES_PASSWORD=password'
        - 'POSTGRES_USER=admin'
      ports:
        - '5433:5432'
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql